name: build
on:
  push:
    branches: [main]
  pull_request:
    paths:
      - '**.go'
      - '.github/workflows/build.yml'
permissions:
  contents: read
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: "1.21"
      - uses: actions/checkout@v4
      - name: Build
        run: make build
